language: objective-c
osx_image: xcode8
xcode_project: SwiftMulticastDelegateDemo.xcodeproj
xcode_scheme: SwiftMulticastDelegateDemo
xcode_sdk: iphonesimulator10.0
notifications:
  email: false
script:
 - xcodebuild -scheme 'SwiftMulticastDelegateDemo' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
